// source: modules/dreamview/proto/camera_update.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.apollo.dreamview.CameraUpdate');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apollo.dreamview.CameraUpdate = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.apollo.dreamview.CameraUpdate.repeatedFields_, null);
};
goog.inherits(proto.apollo.dreamview.CameraUpdate, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apollo.dreamview.CameraUpdate.displayName = 'proto.apollo.dreamview.CameraUpdate';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.apollo.dreamview.CameraUpdate.repeatedFields_ = [1,2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apollo.dreamview.CameraUpdate.prototype.toObject = function(opt_includeInstance) {
  return proto.apollo.dreamview.CameraUpdate.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apollo.dreamview.CameraUpdate} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.dreamview.CameraUpdate.toObject = function(includeInstance, msg) {
  var f, obj = {
    localizationList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 1)) == null ? undefined : f,
    localization2cameraTfList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 2)) == null ? undefined : f,
    image: msg.getImage_asB64(),
    imageAspectRatio: (f = jspb.Message.getOptionalFloatingPointField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


if (jspb.Message.GENERATE_FROM_OBJECT) {

/**
 * The raw object form of CameraUpdate as accepted by the `fromObject` method.
 * @record
 */
proto.apollo.dreamview.CameraUpdate.ObjectFormat = function() {
  /** @type {?|undefined} */
  this.localizationList;

  /** @type {?|undefined} */
  this.localization2cameraTfList;

  /** @type {?|undefined} */
  this.image;

  /** @type {?|undefined} */
  this.imageAspectRatio;
};

/**
 * Loads data from an object into a new instance of this proto.
 * @param {!proto.apollo.dreamview.CameraUpdate.ObjectFormat} obj
 *     The object representation of this proto to load the data from.
 * @return {!proto.apollo.dreamview.CameraUpdate}
 */
proto.apollo.dreamview.CameraUpdate.fromObject = function(obj) {
  var msg = new proto.apollo.dreamview.CameraUpdate();
  obj.localizationList != null && jspb.Message.setField(msg, 1, obj.localizationList);
  obj.localization2cameraTfList != null && jspb.Message.setField(msg, 2, obj.localization2cameraTfList);
  obj.image != null && jspb.Message.setField(msg, 3, obj.image);
  obj.imageAspectRatio != null && jspb.Message.setField(msg, 4, obj.imageAspectRatio);
  return msg;
};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apollo.dreamview.CameraUpdate}
 */
proto.apollo.dreamview.CameraUpdate.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apollo.dreamview.CameraUpdate;
  return proto.apollo.dreamview.CameraUpdate.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apollo.dreamview.CameraUpdate} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apollo.dreamview.CameraUpdate}
 */
proto.apollo.dreamview.CameraUpdate.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addLocalization(values[i]);
      }
      break;
    case 2:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addLocalization2cameraTf(values[i]);
      }
      break;
    case 3:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setImage(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setImageAspectRatio(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apollo.dreamview.CameraUpdate.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apollo.dreamview.CameraUpdate.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apollo.dreamview.CameraUpdate} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.dreamview.CameraUpdate.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLocalizationList();
  if (f.length > 0) {
    writer.writeRepeatedDouble(
      1,
      f
    );
  }
  f = message.getLocalization2cameraTfList();
  if (f.length > 0) {
    writer.writeRepeatedDouble(
      2,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeBytes(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeDouble(
      4,
      f
    );
  }
};


/**
 * repeated double localization = 1;
 * @return {!Array<number>}
 */
proto.apollo.dreamview.CameraUpdate.prototype.getLocalizationList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.apollo.dreamview.CameraUpdate} returns this
 */
proto.apollo.dreamview.CameraUpdate.prototype.setLocalizationList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.apollo.dreamview.CameraUpdate} returns this
 */
proto.apollo.dreamview.CameraUpdate.prototype.addLocalization = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.apollo.dreamview.CameraUpdate} returns this
 */
proto.apollo.dreamview.CameraUpdate.prototype.clearLocalizationList = function() {
  return this.setLocalizationList([]);
};


/**
 * repeated double localization2camera_tf = 2;
 * @return {!Array<number>}
 */
proto.apollo.dreamview.CameraUpdate.prototype.getLocalization2cameraTfList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.apollo.dreamview.CameraUpdate} returns this
 */
proto.apollo.dreamview.CameraUpdate.prototype.setLocalization2cameraTfList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.apollo.dreamview.CameraUpdate} returns this
 */
proto.apollo.dreamview.CameraUpdate.prototype.addLocalization2cameraTf = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.apollo.dreamview.CameraUpdate} returns this
 */
proto.apollo.dreamview.CameraUpdate.prototype.clearLocalization2cameraTfList = function() {
  return this.setLocalization2cameraTfList([]);
};


/**
 * optional bytes image = 3;
 * @return {!(string|Uint8Array)}
 */
proto.apollo.dreamview.CameraUpdate.prototype.getImage = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * optional bytes image = 3;
 * This is a type-conversion wrapper around `getImage()`
 * @return {string}
 */
proto.apollo.dreamview.CameraUpdate.prototype.getImage_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getImage()));
};


/**
 * optional bytes image = 3;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getImage()`
 * @return {!Uint8Array}
 */
proto.apollo.dreamview.CameraUpdate.prototype.getImage_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getImage()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.apollo.dreamview.CameraUpdate} returns this
 */
proto.apollo.dreamview.CameraUpdate.prototype.setImage = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.dreamview.CameraUpdate} returns this
 */
proto.apollo.dreamview.CameraUpdate.prototype.clearImage = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.dreamview.CameraUpdate.prototype.hasImage = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional double image_aspect_ratio = 4;
 * @return {number}
 */
proto.apollo.dreamview.CameraUpdate.prototype.getImageAspectRatio = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.apollo.dreamview.CameraUpdate} returns this
 */
proto.apollo.dreamview.CameraUpdate.prototype.setImageAspectRatio = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.dreamview.CameraUpdate} returns this
 */
proto.apollo.dreamview.CameraUpdate.prototype.clearImageAspectRatio = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.dreamview.CameraUpdate.prototype.hasImageAspectRatio = function() {
  return jspb.Message.getField(this, 4) != null;
};


