// source: modules/dreamview/proto/hmi_mode.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.apollo.dreamview.CyberModule');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apollo.dreamview.CyberModule = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.apollo.dreamview.CyberModule.repeatedFields_, null);
};
goog.inherits(proto.apollo.dreamview.CyberModule, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apollo.dreamview.CyberModule.displayName = 'proto.apollo.dreamview.CyberModule';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.apollo.dreamview.CyberModule.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apollo.dreamview.CyberModule.prototype.toObject = function(opt_includeInstance) {
  return proto.apollo.dreamview.CyberModule.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apollo.dreamview.CyberModule} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.dreamview.CyberModule.toObject = function(includeInstance, msg) {
  var f, obj = {
    dagFilesList: (f = jspb.Message.getRepeatedField(msg, 1)) == null ? undefined : f,
    requiredForSafety: jspb.Message.getBooleanFieldWithDefault(msg, 2, true),
    processGroup: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


if (jspb.Message.GENERATE_FROM_OBJECT) {

/**
 * The raw object form of CyberModule as accepted by the `fromObject` method.
 * @record
 */
proto.apollo.dreamview.CyberModule.ObjectFormat = function() {
  /** @type {?|undefined} */
  this.dagFilesList;

  /** @type {?|undefined} */
  this.requiredForSafety;

  /** @type {?|undefined} */
  this.processGroup;
};

/**
 * Loads data from an object into a new instance of this proto.
 * @param {!proto.apollo.dreamview.CyberModule.ObjectFormat} obj
 *     The object representation of this proto to load the data from.
 * @return {!proto.apollo.dreamview.CyberModule}
 */
proto.apollo.dreamview.CyberModule.fromObject = function(obj) {
  var msg = new proto.apollo.dreamview.CyberModule();
  obj.dagFilesList != null && jspb.Message.setField(msg, 1, obj.dagFilesList);
  obj.requiredForSafety != null && jspb.Message.setField(msg, 2, obj.requiredForSafety);
  obj.processGroup != null && jspb.Message.setField(msg, 3, obj.processGroup);
  return msg;
};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apollo.dreamview.CyberModule}
 */
proto.apollo.dreamview.CyberModule.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apollo.dreamview.CyberModule;
  return proto.apollo.dreamview.CyberModule.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apollo.dreamview.CyberModule} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apollo.dreamview.CyberModule}
 */
proto.apollo.dreamview.CyberModule.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addDagFiles(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setRequiredForSafety(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setProcessGroup(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apollo.dreamview.CyberModule.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apollo.dreamview.CyberModule.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apollo.dreamview.CyberModule} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.dreamview.CyberModule.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDagFilesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeBool(
      2,
      f
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * repeated string dag_files = 1;
 * @return {!Array<string>}
 */
proto.apollo.dreamview.CyberModule.prototype.getDagFilesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.apollo.dreamview.CyberModule} returns this
 */
proto.apollo.dreamview.CyberModule.prototype.setDagFilesList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.apollo.dreamview.CyberModule} returns this
 */
proto.apollo.dreamview.CyberModule.prototype.addDagFiles = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.apollo.dreamview.CyberModule} returns this
 */
proto.apollo.dreamview.CyberModule.prototype.clearDagFilesList = function() {
  return this.setDagFilesList([]);
};


/**
 * optional bool required_for_safety = 2;
 * @return {boolean}
 */
proto.apollo.dreamview.CyberModule.prototype.getRequiredForSafety = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, true));
};


/**
 * @param {boolean} value
 * @return {!proto.apollo.dreamview.CyberModule} returns this
 */
proto.apollo.dreamview.CyberModule.prototype.setRequiredForSafety = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.dreamview.CyberModule} returns this
 */
proto.apollo.dreamview.CyberModule.prototype.clearRequiredForSafety = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.dreamview.CyberModule.prototype.hasRequiredForSafety = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string process_group = 3;
 * @return {string}
 */
proto.apollo.dreamview.CyberModule.prototype.getProcessGroup = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.apollo.dreamview.CyberModule} returns this
 */
proto.apollo.dreamview.CyberModule.prototype.setProcessGroup = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.dreamview.CyberModule} returns this
 */
proto.apollo.dreamview.CyberModule.prototype.clearProcessGroup = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.dreamview.CyberModule.prototype.hasProcessGroup = function() {
  return jspb.Message.getField(this, 3) != null;
};


