// source: modules/common/proto/pnc_point.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.apollo.common.GaussianInfo');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apollo.common.GaussianInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.apollo.common.GaussianInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apollo.common.GaussianInfo.displayName = 'proto.apollo.common.GaussianInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apollo.common.GaussianInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.apollo.common.GaussianInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apollo.common.GaussianInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.common.GaussianInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    sigmaX: (f = jspb.Message.getOptionalFloatingPointField(msg, 1)) == null ? undefined : f,
    sigmaY: (f = jspb.Message.getOptionalFloatingPointField(msg, 2)) == null ? undefined : f,
    correlation: (f = jspb.Message.getOptionalFloatingPointField(msg, 3)) == null ? undefined : f,
    areaProbability: (f = jspb.Message.getOptionalFloatingPointField(msg, 4)) == null ? undefined : f,
    ellipseA: (f = jspb.Message.getOptionalFloatingPointField(msg, 5)) == null ? undefined : f,
    ellipseB: (f = jspb.Message.getOptionalFloatingPointField(msg, 6)) == null ? undefined : f,
    thetaA: (f = jspb.Message.getOptionalFloatingPointField(msg, 7)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apollo.common.GaussianInfo}
 */
proto.apollo.common.GaussianInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apollo.common.GaussianInfo;
  return proto.apollo.common.GaussianInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apollo.common.GaussianInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apollo.common.GaussianInfo}
 */
proto.apollo.common.GaussianInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSigmaX(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSigmaY(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setCorrelation(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAreaProbability(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setEllipseA(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setEllipseB(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setThetaA(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apollo.common.GaussianInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apollo.common.GaussianInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apollo.common.GaussianInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.common.GaussianInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeDouble(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 6));
  if (f != null) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeDouble(
      7,
      f
    );
  }
};


/**
 * optional double sigma_x = 1;
 * @return {number}
 */
proto.apollo.common.GaussianInfo.prototype.getSigmaX = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.apollo.common.GaussianInfo} returns this
 */
proto.apollo.common.GaussianInfo.prototype.setSigmaX = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.common.GaussianInfo} returns this
 */
proto.apollo.common.GaussianInfo.prototype.clearSigmaX = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.common.GaussianInfo.prototype.hasSigmaX = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional double sigma_y = 2;
 * @return {number}
 */
proto.apollo.common.GaussianInfo.prototype.getSigmaY = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.apollo.common.GaussianInfo} returns this
 */
proto.apollo.common.GaussianInfo.prototype.setSigmaY = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.common.GaussianInfo} returns this
 */
proto.apollo.common.GaussianInfo.prototype.clearSigmaY = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.common.GaussianInfo.prototype.hasSigmaY = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional double correlation = 3;
 * @return {number}
 */
proto.apollo.common.GaussianInfo.prototype.getCorrelation = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.apollo.common.GaussianInfo} returns this
 */
proto.apollo.common.GaussianInfo.prototype.setCorrelation = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.common.GaussianInfo} returns this
 */
proto.apollo.common.GaussianInfo.prototype.clearCorrelation = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.common.GaussianInfo.prototype.hasCorrelation = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional double area_probability = 4;
 * @return {number}
 */
proto.apollo.common.GaussianInfo.prototype.getAreaProbability = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.apollo.common.GaussianInfo} returns this
 */
proto.apollo.common.GaussianInfo.prototype.setAreaProbability = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.common.GaussianInfo} returns this
 */
proto.apollo.common.GaussianInfo.prototype.clearAreaProbability = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.common.GaussianInfo.prototype.hasAreaProbability = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional double ellipse_a = 5;
 * @return {number}
 */
proto.apollo.common.GaussianInfo.prototype.getEllipseA = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.apollo.common.GaussianInfo} returns this
 */
proto.apollo.common.GaussianInfo.prototype.setEllipseA = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.common.GaussianInfo} returns this
 */
proto.apollo.common.GaussianInfo.prototype.clearEllipseA = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.common.GaussianInfo.prototype.hasEllipseA = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional double ellipse_b = 6;
 * @return {number}
 */
proto.apollo.common.GaussianInfo.prototype.getEllipseB = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.apollo.common.GaussianInfo} returns this
 */
proto.apollo.common.GaussianInfo.prototype.setEllipseB = function(value) {
  return jspb.Message.setField(this, 6, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.common.GaussianInfo} returns this
 */
proto.apollo.common.GaussianInfo.prototype.clearEllipseB = function() {
  return jspb.Message.setField(this, 6, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.common.GaussianInfo.prototype.hasEllipseB = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional double theta_a = 7;
 * @return {number}
 */
proto.apollo.common.GaussianInfo.prototype.getThetaA = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 7, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.apollo.common.GaussianInfo} returns this
 */
proto.apollo.common.GaussianInfo.prototype.setThetaA = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.common.GaussianInfo} returns this
 */
proto.apollo.common.GaussianInfo.prototype.clearThetaA = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.common.GaussianInfo.prototype.hasThetaA = function() {
  return jspb.Message.getField(this, 7) != null;
};


