// source: modules/map/proto/map_lane.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.apollo.hdmap.LaneBoundaryType');
goog.provide('proto.apollo.hdmap.LaneBoundaryType.Type');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apollo.hdmap.LaneBoundaryType = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.apollo.hdmap.LaneBoundaryType.repeatedFields_, null);
};
goog.inherits(proto.apollo.hdmap.LaneBoundaryType, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apollo.hdmap.LaneBoundaryType.displayName = 'proto.apollo.hdmap.LaneBoundaryType';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.apollo.hdmap.LaneBoundaryType.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apollo.hdmap.LaneBoundaryType.prototype.toObject = function(opt_includeInstance) {
  return proto.apollo.hdmap.LaneBoundaryType.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apollo.hdmap.LaneBoundaryType} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.hdmap.LaneBoundaryType.toObject = function(includeInstance, msg) {
  var f, obj = {
    s: (f = jspb.Message.getOptionalFloatingPointField(msg, 1)) == null ? undefined : f,
    typesList: (f = jspb.Message.getRepeatedField(msg, 2)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apollo.hdmap.LaneBoundaryType}
 */
proto.apollo.hdmap.LaneBoundaryType.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apollo.hdmap.LaneBoundaryType;
  return proto.apollo.hdmap.LaneBoundaryType.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apollo.hdmap.LaneBoundaryType} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apollo.hdmap.LaneBoundaryType}
 */
proto.apollo.hdmap.LaneBoundaryType.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setS(value);
      break;
    case 2:
      var values = /** @type {!Array<!proto.apollo.hdmap.LaneBoundaryType.Type>} */ (reader.isDelimited() ? reader.readPackedEnum() : [reader.readEnum()]);
      for (var i = 0; i < values.length; i++) {
        msg.addTypes(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apollo.hdmap.LaneBoundaryType.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apollo.hdmap.LaneBoundaryType.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apollo.hdmap.LaneBoundaryType} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.hdmap.LaneBoundaryType.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeDouble(
      1,
      f
    );
  }
  f = message.getTypesList();
  if (f.length > 0) {
    writer.writeRepeatedEnum(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.apollo.hdmap.LaneBoundaryType.Type = {
  UNKNOWN: 0,
  DOTTED_YELLOW: 1,
  DOTTED_WHITE: 2,
  SOLID_YELLOW: 3,
  SOLID_WHITE: 4,
  DOUBLE_YELLOW: 5,
  CURB: 6
};

/**
 * optional double s = 1;
 * @return {number}
 */
proto.apollo.hdmap.LaneBoundaryType.prototype.getS = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 1, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.apollo.hdmap.LaneBoundaryType} returns this
 */
proto.apollo.hdmap.LaneBoundaryType.prototype.setS = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.hdmap.LaneBoundaryType} returns this
 */
proto.apollo.hdmap.LaneBoundaryType.prototype.clearS = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.hdmap.LaneBoundaryType.prototype.hasS = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Type types = 2;
 * @return {!Array<!proto.apollo.hdmap.LaneBoundaryType.Type>}
 */
proto.apollo.hdmap.LaneBoundaryType.prototype.getTypesList = function() {
  return /** @type {!Array<!proto.apollo.hdmap.LaneBoundaryType.Type>} */ (jspb.Message.getRepeatedField(this, 2));
};


/**
 * @param {!Array<!proto.apollo.hdmap.LaneBoundaryType.Type>} value
 * @return {!proto.apollo.hdmap.LaneBoundaryType} returns this
 */
proto.apollo.hdmap.LaneBoundaryType.prototype.setTypesList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {!proto.apollo.hdmap.LaneBoundaryType.Type} value
 * @param {number=} opt_index
 * @return {!proto.apollo.hdmap.LaneBoundaryType} returns this
 */
proto.apollo.hdmap.LaneBoundaryType.prototype.addTypes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.apollo.hdmap.LaneBoundaryType} returns this
 */
proto.apollo.hdmap.LaneBoundaryType.prototype.clearTypesList = function() {
  return this.setTypesList([]);
};


