// source: modules/map/tools/map_datachecker/proto/collection_check_message.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.apollo.hdmap.LoopsVerifyRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.apollo.hdmap.VerifyRange');

goog.forwardDeclare('proto.apollo.hdmap.CmdType');
goog.forwardDeclare('proto.apollo.hdmap.DataType');
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apollo.hdmap.LoopsVerifyRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.apollo.hdmap.LoopsVerifyRequest.repeatedFields_, null);
};
goog.inherits(proto.apollo.hdmap.LoopsVerifyRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apollo.hdmap.LoopsVerifyRequest.displayName = 'proto.apollo.hdmap.LoopsVerifyRequest';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.apollo.hdmap.LoopsVerifyRequest.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apollo.hdmap.LoopsVerifyRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.apollo.hdmap.LoopsVerifyRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apollo.hdmap.LoopsVerifyRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.hdmap.LoopsVerifyRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    cmd: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    type: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    rangeList: jspb.Message.toObjectList(msg.getRangeList(),
    proto.apollo.hdmap.VerifyRange.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apollo.hdmap.LoopsVerifyRequest}
 */
proto.apollo.hdmap.LoopsVerifyRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apollo.hdmap.LoopsVerifyRequest;
  return proto.apollo.hdmap.LoopsVerifyRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apollo.hdmap.LoopsVerifyRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apollo.hdmap.LoopsVerifyRequest}
 */
proto.apollo.hdmap.LoopsVerifyRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.apollo.hdmap.CmdType} */ (reader.readEnum());
      msg.setCmd(value);
      break;
    case 2:
      var value = /** @type {!proto.apollo.hdmap.DataType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 3:
      var value = new proto.apollo.hdmap.VerifyRange;
      reader.readMessage(value,proto.apollo.hdmap.VerifyRange.deserializeBinaryFromReader);
      msg.addRange(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apollo.hdmap.LoopsVerifyRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apollo.hdmap.LoopsVerifyRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apollo.hdmap.LoopsVerifyRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.hdmap.LoopsVerifyRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.apollo.hdmap.CmdType} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {!proto.apollo.hdmap.DataType} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getRangeList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.apollo.hdmap.VerifyRange.serializeBinaryToWriter
    );
  }
};


/**
 * optional CmdType cmd = 1;
 * @return {!proto.apollo.hdmap.CmdType}
 */
proto.apollo.hdmap.LoopsVerifyRequest.prototype.getCmd = function() {
  return /** @type {!proto.apollo.hdmap.CmdType} */ (jspb.Message.getFieldWithDefault(this, 1, 1));
};


/**
 * @param {!proto.apollo.hdmap.CmdType} value
 * @return {!proto.apollo.hdmap.LoopsVerifyRequest} returns this
 */
proto.apollo.hdmap.LoopsVerifyRequest.prototype.setCmd = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.hdmap.LoopsVerifyRequest} returns this
 */
proto.apollo.hdmap.LoopsVerifyRequest.prototype.clearCmd = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.hdmap.LoopsVerifyRequest.prototype.hasCmd = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional DataType type = 2;
 * @return {!proto.apollo.hdmap.DataType}
 */
proto.apollo.hdmap.LoopsVerifyRequest.prototype.getType = function() {
  return /** @type {!proto.apollo.hdmap.DataType} */ (jspb.Message.getFieldWithDefault(this, 2, 1));
};


/**
 * @param {!proto.apollo.hdmap.DataType} value
 * @return {!proto.apollo.hdmap.LoopsVerifyRequest} returns this
 */
proto.apollo.hdmap.LoopsVerifyRequest.prototype.setType = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.hdmap.LoopsVerifyRequest} returns this
 */
proto.apollo.hdmap.LoopsVerifyRequest.prototype.clearType = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.hdmap.LoopsVerifyRequest.prototype.hasType = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated VerifyRange range = 3;
 * @return {!Array<!proto.apollo.hdmap.VerifyRange>}
 */
proto.apollo.hdmap.LoopsVerifyRequest.prototype.getRangeList = function() {
  return /** @type{!Array<!proto.apollo.hdmap.VerifyRange>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.apollo.hdmap.VerifyRange, 3));
};


/**
 * @param {!Array<!proto.apollo.hdmap.VerifyRange>} value
 * @return {!proto.apollo.hdmap.LoopsVerifyRequest} returns this
*/
proto.apollo.hdmap.LoopsVerifyRequest.prototype.setRangeList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.apollo.hdmap.VerifyRange=} opt_value
 * @param {number=} opt_index
 * @return {!proto.apollo.hdmap.VerifyRange}
 */
proto.apollo.hdmap.LoopsVerifyRequest.prototype.addRange = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.apollo.hdmap.VerifyRange, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.apollo.hdmap.LoopsVerifyRequest} returns this
 */
proto.apollo.hdmap.LoopsVerifyRequest.prototype.clearRangeList = function() {
  return this.setRangeList([]);
};


