// source: modules/dreamview/proto/preprocess_table.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.apollo.dreamview.PreprocessTable');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.apollo.dreamview.CameraConfig');
goog.require('proto.apollo.dreamview.LidarConfig');
goog.require('proto.apollo.dreamview.Progress');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apollo.dreamview.PreprocessTable = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.apollo.dreamview.PreprocessTable.repeatedFields_, null);
};
goog.inherits(proto.apollo.dreamview.PreprocessTable, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apollo.dreamview.PreprocessTable.displayName = 'proto.apollo.dreamview.PreprocessTable';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.apollo.dreamview.PreprocessTable.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apollo.dreamview.PreprocessTable.prototype.toObject = function(opt_includeInstance) {
  return proto.apollo.dreamview.PreprocessTable.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apollo.dreamview.PreprocessTable} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.dreamview.PreprocessTable.toObject = function(includeInstance, msg) {
  var f, obj = {
    lidarConfigList: jspb.Message.toObjectList(msg.getLidarConfigList(),
    proto.apollo.dreamview.LidarConfig.toObject, includeInstance),
    cameraConfig: (f = msg.getCameraConfig()) && proto.apollo.dreamview.CameraConfig.toObject(includeInstance, f),
    mainSensor: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    progress: (f = msg.getProgress()) && proto.apollo.dreamview.Progress.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


if (jspb.Message.GENERATE_FROM_OBJECT) {

/**
 * The raw object form of PreprocessTable as accepted by the `fromObject` method.
 * @record
 */
proto.apollo.dreamview.PreprocessTable.ObjectFormat = function() {
  /** @type {?|undefined} */
  this.lidarConfigList;

  /** @type {?|undefined} */
  this.cameraConfig;

  /** @type {?|undefined} */
  this.mainSensor;

  /** @type {?|undefined} */
  this.progress;
};

/**
 * Loads data from an object into a new instance of this proto.
 * @param {!proto.apollo.dreamview.PreprocessTable.ObjectFormat} obj
 *     The object representation of this proto to load the data from.
 * @return {!proto.apollo.dreamview.PreprocessTable}
 */
proto.apollo.dreamview.PreprocessTable.fromObject = function(obj) {
  var msg = new proto.apollo.dreamview.PreprocessTable();
  obj.lidarConfigList && jspb.Message.setRepeatedWrapperField(
      msg, 1, obj.lidarConfigList.map(
          proto.apollo.dreamview.LidarConfig.fromObject));
  obj.cameraConfig && jspb.Message.setWrapperField(
      msg, 2, proto.apollo.dreamview.CameraConfig.fromObject(obj.cameraConfig));
  obj.mainSensor != null && jspb.Message.setField(msg, 3, obj.mainSensor);
  obj.progress && jspb.Message.setWrapperField(
      msg, 4, proto.apollo.dreamview.Progress.fromObject(obj.progress));
  return msg;
};
}

/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apollo.dreamview.PreprocessTable}
 */
proto.apollo.dreamview.PreprocessTable.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apollo.dreamview.PreprocessTable;
  return proto.apollo.dreamview.PreprocessTable.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apollo.dreamview.PreprocessTable} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apollo.dreamview.PreprocessTable}
 */
proto.apollo.dreamview.PreprocessTable.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.apollo.dreamview.LidarConfig;
      reader.readMessage(value,proto.apollo.dreamview.LidarConfig.deserializeBinaryFromReader);
      msg.addLidarConfig(value);
      break;
    case 2:
      var value = new proto.apollo.dreamview.CameraConfig;
      reader.readMessage(value,proto.apollo.dreamview.CameraConfig.deserializeBinaryFromReader);
      msg.setCameraConfig(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setMainSensor(value);
      break;
    case 4:
      var value = new proto.apollo.dreamview.Progress;
      reader.readMessage(value,proto.apollo.dreamview.Progress.deserializeBinaryFromReader);
      msg.setProgress(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apollo.dreamview.PreprocessTable.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apollo.dreamview.PreprocessTable.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apollo.dreamview.PreprocessTable} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.dreamview.PreprocessTable.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLidarConfigList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.apollo.dreamview.LidarConfig.serializeBinaryToWriter
    );
  }
  f = message.getCameraConfig();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.apollo.dreamview.CameraConfig.serializeBinaryToWriter
    );
  }
  f = /** @type {string} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getProgress();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.apollo.dreamview.Progress.serializeBinaryToWriter
    );
  }
};


/**
 * repeated LidarConfig lidar_config = 1;
 * @return {!Array<!proto.apollo.dreamview.LidarConfig>}
 */
proto.apollo.dreamview.PreprocessTable.prototype.getLidarConfigList = function() {
  return /** @type{!Array<!proto.apollo.dreamview.LidarConfig>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.apollo.dreamview.LidarConfig, 1));
};


/**
 * @param {!Array<!proto.apollo.dreamview.LidarConfig>} value
 * @return {!proto.apollo.dreamview.PreprocessTable} returns this
*/
proto.apollo.dreamview.PreprocessTable.prototype.setLidarConfigList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.apollo.dreamview.LidarConfig=} opt_value
 * @param {number=} opt_index
 * @return {!proto.apollo.dreamview.LidarConfig}
 */
proto.apollo.dreamview.PreprocessTable.prototype.addLidarConfig = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.apollo.dreamview.LidarConfig, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.apollo.dreamview.PreprocessTable} returns this
 */
proto.apollo.dreamview.PreprocessTable.prototype.clearLidarConfigList = function() {
  return this.setLidarConfigList([]);
};


/**
 * optional CameraConfig camera_config = 2;
 * @return {?proto.apollo.dreamview.CameraConfig}
 */
proto.apollo.dreamview.PreprocessTable.prototype.getCameraConfig = function() {
  return /** @type{?proto.apollo.dreamview.CameraConfig} */ (
    jspb.Message.getWrapperField(this, proto.apollo.dreamview.CameraConfig, 2));
};


/**
 * @param {?proto.apollo.dreamview.CameraConfig|undefined} value
 * @return {!proto.apollo.dreamview.PreprocessTable} returns this
*/
proto.apollo.dreamview.PreprocessTable.prototype.setCameraConfig = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.apollo.dreamview.PreprocessTable} returns this
 */
proto.apollo.dreamview.PreprocessTable.prototype.clearCameraConfig = function() {
  return this.setCameraConfig(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.dreamview.PreprocessTable.prototype.hasCameraConfig = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string main_sensor = 3;
 * @return {string}
 */
proto.apollo.dreamview.PreprocessTable.prototype.getMainSensor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.apollo.dreamview.PreprocessTable} returns this
 */
proto.apollo.dreamview.PreprocessTable.prototype.setMainSensor = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.apollo.dreamview.PreprocessTable} returns this
 */
proto.apollo.dreamview.PreprocessTable.prototype.clearMainSensor = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.dreamview.PreprocessTable.prototype.hasMainSensor = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional Progress progress = 4;
 * @return {?proto.apollo.dreamview.Progress}
 */
proto.apollo.dreamview.PreprocessTable.prototype.getProgress = function() {
  return /** @type{?proto.apollo.dreamview.Progress} */ (
    jspb.Message.getWrapperField(this, proto.apollo.dreamview.Progress, 4));
};


/**
 * @param {?proto.apollo.dreamview.Progress|undefined} value
 * @return {!proto.apollo.dreamview.PreprocessTable} returns this
*/
proto.apollo.dreamview.PreprocessTable.prototype.setProgress = function(value) {
  return jspb.Message.setWrapperField(this, 4, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.apollo.dreamview.PreprocessTable} returns this
 */
proto.apollo.dreamview.PreprocessTable.prototype.clearProgress = function() {
  return this.setProgress(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.dreamview.PreprocessTable.prototype.hasProgress = function() {
  return jspb.Message.getField(this, 4) != null;
};


