// source: modules/map/tools/map_datachecker/proto/collection_check_message.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.apollo.hdmap.VerifyResult');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.apollo.hdmap.FrameRate');
goog.require('proto.apollo.hdmap.TopicResult');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.apollo.hdmap.VerifyResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.apollo.hdmap.VerifyResult.repeatedFields_, null);
};
goog.inherits(proto.apollo.hdmap.VerifyResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.apollo.hdmap.VerifyResult.displayName = 'proto.apollo.hdmap.VerifyResult';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.apollo.hdmap.VerifyResult.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.apollo.hdmap.VerifyResult.prototype.toObject = function(opt_includeInstance) {
  return proto.apollo.hdmap.VerifyResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.apollo.hdmap.VerifyResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.hdmap.VerifyResult.toObject = function(includeInstance, msg) {
  var f, obj = {
    topics: (f = msg.getTopics()) && proto.apollo.hdmap.TopicResult.toObject(includeInstance, f),
    ratesList: jspb.Message.toObjectList(msg.getRatesList(),
    proto.apollo.hdmap.FrameRate.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.apollo.hdmap.VerifyResult}
 */
proto.apollo.hdmap.VerifyResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.apollo.hdmap.VerifyResult;
  return proto.apollo.hdmap.VerifyResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.apollo.hdmap.VerifyResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.apollo.hdmap.VerifyResult}
 */
proto.apollo.hdmap.VerifyResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.apollo.hdmap.TopicResult;
      reader.readMessage(value,proto.apollo.hdmap.TopicResult.deserializeBinaryFromReader);
      msg.setTopics(value);
      break;
    case 2:
      var value = new proto.apollo.hdmap.FrameRate;
      reader.readMessage(value,proto.apollo.hdmap.FrameRate.deserializeBinaryFromReader);
      msg.addRates(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.apollo.hdmap.VerifyResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.apollo.hdmap.VerifyResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.apollo.hdmap.VerifyResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.apollo.hdmap.VerifyResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTopics();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.apollo.hdmap.TopicResult.serializeBinaryToWriter
    );
  }
  f = message.getRatesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.apollo.hdmap.FrameRate.serializeBinaryToWriter
    );
  }
};


/**
 * optional TopicResult topics = 1;
 * @return {?proto.apollo.hdmap.TopicResult}
 */
proto.apollo.hdmap.VerifyResult.prototype.getTopics = function() {
  return /** @type{?proto.apollo.hdmap.TopicResult} */ (
    jspb.Message.getWrapperField(this, proto.apollo.hdmap.TopicResult, 1));
};


/**
 * @param {?proto.apollo.hdmap.TopicResult|undefined} value
 * @return {!proto.apollo.hdmap.VerifyResult} returns this
*/
proto.apollo.hdmap.VerifyResult.prototype.setTopics = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.apollo.hdmap.VerifyResult} returns this
 */
proto.apollo.hdmap.VerifyResult.prototype.clearTopics = function() {
  return this.setTopics(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.apollo.hdmap.VerifyResult.prototype.hasTopics = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated FrameRate rates = 2;
 * @return {!Array<!proto.apollo.hdmap.FrameRate>}
 */
proto.apollo.hdmap.VerifyResult.prototype.getRatesList = function() {
  return /** @type{!Array<!proto.apollo.hdmap.FrameRate>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.apollo.hdmap.FrameRate, 2));
};


/**
 * @param {!Array<!proto.apollo.hdmap.FrameRate>} value
 * @return {!proto.apollo.hdmap.VerifyResult} returns this
*/
proto.apollo.hdmap.VerifyResult.prototype.setRatesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.apollo.hdmap.FrameRate=} opt_value
 * @param {number=} opt_index
 * @return {!proto.apollo.hdmap.FrameRate}
 */
proto.apollo.hdmap.VerifyResult.prototype.addRates = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.apollo.hdmap.FrameRate, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.apollo.hdmap.VerifyResult} returns this
 */
proto.apollo.hdmap.VerifyResult.prototype.clearRatesList = function() {
  return this.setRatesList([]);
};


